# Generated by Django 3.0.6 on 2020-05-27 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePolo', models.CharField(max_length=100)),
                ('qtdEstoque', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialTerminal', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('idPoloT', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Polo')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHistorico', models.DateTimeField(auto_now=True)),
                ('idPoloH', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Polo')),
                ('idTerminalH', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Terminal')),
            ],
        ),
    ]
